### ISSUE TITLE
Me want documentation

### ISSUE THREAD

**Issue by IAFahim** [uzzalcontact/SuperHeroApi#1]
![lots of it](https://media.giphy.com/media/heIX5HfWgEYlW/giphy.gif)

**Comment by mortuzahossain** [comment]
Me😂😂😂😂 don't give documentation😂😂😂😂

**Comment by IAFahim** [comment]
Readme would work too 😗

**Comment by mortuzahossain** [comment]
Brother, it is a learning purpose app just CRUD nothing else.

Thank you for being so interested
